name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deploy - staging
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v4
      - uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/deploy@v1
        with:
          app-to-deploy: "annuaire-entreprises-api-proxy"
          app-repository: "https://github.com/annuaire-entreprises-data-gouv-fr/api-proxy.git"
          app-shortname: "api-proxy"
          version: "main"
          environment: "staging"
          ssh-key: ${{ secrets.SSH_MACHINE_USER_PRIVATE_KEY }}
          ssh-host: $${{ secrets.SSH_HOST_STAGING }}
          notify-on-failure: true
          notify-on-success: false
          notify-webhook: ${{ secrets.DEV_EVENT_HOOK }}

  deploy-production:
    name: Deploy - production
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    environment:
      name: production

    steps:
      - uses: actions/checkout@v4
      - uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/deploy@v1
        with:
          app-to-deploy: "annuaire-entreprises-api-proxy"
          app-repository: "https://github.com/annuaire-entreprises-data-gouv-fr/api-proxy.git"
          app-shortname: "api-proxy"
          version: "main"
          environment: "production"
          ssh-key: ${{ secrets.SSH_MACHINE_USER_PRIVATE_KEY }}
          ssh-host: $${{ secrets.SSH_HOST_PRODUCTION }}
          notify-on-failure: true
          notify-on-success: true
          notify-webhook: ${{ secrets.DEV_EVENT_HOOK }}
