# This workflow will do a clean install of node dependencies, build the source code and run tests

name: "Pre-merge checks"
permissions:
  contents: read

on:
  pull_request:
    branches: [main]

# Be extremely careful as the env variables defined here are accessible by all the actions of the workflow.
# For critical env variable, declare it within the action.
env:
  node-version: 22.22.2
jobs:
  dependencies:
    name: "Install dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: Enable pnpm
        shell: bash
        run: corepack enable pnpm
      - name: Cache node modules
        uses: actions/cache@v3
        id: restore-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-cache-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile --prod=false --ignore-scripts

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [dependencies]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: Enable pnpm
        shell: bash
        run: corepack enable pnpm
      - name: Load node modules
        uses: actions/cache@v4
        id: restore-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Run linter
        run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [dependencies]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: Enable pnpm
        shell: bash
        run: corepack enable pnpm
      - name: Load node modules
        uses: actions/cache@v4
        id: restore-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Build
        run: pnpm build
      - name: Cache build
        uses: actions/cache@v4
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: [dependencies]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: Enable pnpm
        shell: bash
        run: corepack enable pnpm
      - name: Load node modules
        uses: actions/cache@v4
        id: restore-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Run unit tests
        run: |
          pnpm test
